version: "3.9"
services:
  web:
    image: nextjs-app
    ports:
      - "3000:3000"
    environment:
      JAVA_SIDECAR_HOST: "host.docker.internal"
  api:
    image: java-sidecar
    ports:
      - "8080:8080"
    environment:
      FLASK_DEBUG: "true"
