version: "3.9"
services:
  web:
    image: nextjs-docker
    ports:
      - "3000:3000"
    environment:
      FLASK_DEBUG: "true"
  api:
    image: java-sidecar
    ports:
      - "8080:8080"
    environment:
      FLASK_DEBUG: "true"
