apiVersion: v1
kind: Service
metadata:
  name: nextjs-with-java-sidecar-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: nextjs-with-java-sidecar-pod
