apiVersion: v1
kind: Pod
metadata:
  name: nextjs-with-java-sidecar-pod
  labels:
    app: nextjs-with-java-sidecar-pod
spec:
  containers:
    - name: nextjs-app
      image: nextjs-app
      imagePullPolicy: Never
      ports:
        - containerPort: 3000
          protocol: TCP
      env:
        - name: JAVA_SIDECAR_HOST
          valueFrom:
            fieldRef:
              fieldPath: spec.containers[1].env[0].value
    - name: java-sidecar
      image: java-sidecar
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
          protocol: TCP
      env:
        - name: JAVA_SIDECAR_HOST
          value: host.docker.internal
  hostAliases:
    - ip: 192.168.49.1
      hostnames:
        - host.minikube.internal
